spring:
  datasource:
    username: postgres
    password: postgres
    url: 'jdbc:postgresql://localhost:5432/postgres?currentSchema=liquibase'
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: true
