spring:
  datasource:
    username: postgres
    password: postgres
    url: 'jdbc:postgresql://localhost:5432/postgres?currentSchema=fly'
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  flyway:
    locations: classpath:db/migration
    enabled: true

