spring:
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  cache:
    redis:
      time-to-live: 10m
  data:
    redis:
      host: localhost
      port: 6379
#      redisga ulanis uchun  username kerak emas time to live bu cashni tozalanish vaqti 10 min
